[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = ["dotnet restore", "dotnet build --configuration Release --no-restore"]

[phases.start]
cmd = "cd CashVouchersManager.API && dotnet run --configuration Release --no-build --urls http://0.0.0.0:$PORT"
