[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
    "dotnet publish CashVouchersManager.API/CashVouchersManager.API.csproj -c Release -o /app/out --self-contained true --runtime linux-x64 /p:PublishSingleFile=false"
]

[start]
cmd = "cd /app/out && ./CashVouchersManager.API --urls http://0.0.0.0:$PORT"
